#:schema node_modules/wrangler/config-schema.json
name = "portfolio"
compatibility_date = "2024-09-25"
main = "./dist/_worker.js"

routes = [
	{ pattern = "cjamal.com", custom_domain = true },
	{ pattern = "shrjamal.com", custom_domain = true },
]

[assets]
binding = "ASSETS"
directory = "./dist"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true

[vars]
SITE = "https://shrjamal.com"
